name: AT
main: cn.iqianye.MinecraftPlugins.AT.Main
version: 1.0-beta
author: 真心
description: §a让MC可以像QQ群一样可以@别人 §c原作者： Brian & fyfly & nFeng & connection_lost
commands:
   at:
      description: help
      usage: /at